import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavbarComponent from "../components/Navbar";
import Login from "../pages/auth/login";
("react-redux");
import { useDispatch, useSelector } from "react-redux";

import { useEffect } from "react";
import { useRouter } from "next/router";
export default function Start() {
  const authSelector = useSelector((state) => state.auth);
  const router = useRouter();

  // useEffect(() => {
  //   if (authSelector?.id) {
  //     router.push("/");
  //   }
  // }, [authSelector?.id]);
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <NavbarComponent /> */}
      <Login />
    </>
  );
}
